config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  get 'admin/home'

  get 'admin/new_user' => 'admin#new_user', as: :admin_new_user
  post 'admin/create_user' => 'admin#create_user', as: :admin_create_user
  get 'admin/edit' => 'admin#edit', as: :admin_edit
  patch 'admin/update' => 'admin#update', as: :admin_update

  get 'home/index'
  root 'home#index'

  resources :programmes

  resources :resources

  resources :scriptures

  resources :songs

  devise_for :users, except: :create

  resources :users, except: :create

end

app/models/scripture.rb
class Scripture < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :programmes

end

app/controllers/scriptures_controller.rb
class ScripturesController < ApplicationController
  before_filter :require_login
  before_action :set_scripture, only: [:show, :edit, :update, :destroy]

  # GET /scriptures
  # GET /scriptures.json
  def index
    @scriptures = Scripture.where(:user_id => current_user.id)
  end

  # GET /scriptures/1
  # GET /scriptures/1.json
  def show
  end

  # GET /scriptures/new
  def new
    @scripture = Scripture.new
  end

  # GET /scriptures/1/edit
  def edit
  end

  # POST /scriptures
  # POST /scriptures.json
  def create
    @scripture = Scripture.new(scripture_params)

    respond_to do |format|
      if @scripture.save
        format.html { redirect_to @scripture, notice: 'Scripture was successfully created.' }
        format.json { render :show, status: :created, location: @scripture }
      else
        format.html { render :new }
        format.json { render json: @scripture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scriptures/1
  # PATCH/PUT /scriptures/1.json
  def update
    respond_to do |format|
      if @scripture.update(scripture_params)
        format.html { redirect_to @scripture, notice: 'Scripture was successfully updated.' }
        format.json { render :show, status: :ok, location: @scripture }
      else
        format.html { render :edit }
        format.json { render json: @scripture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scriptures/1
  # DELETE /scriptures/1.json
  def destroy
    @scripture.destroy
    respond_to do |format|
      format.html { redirect_to scriptures_url, notice: 'Scripture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scripture
      @scripture = Scripture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scripture_params
      params.require(:scripture).permit(
                                        :title,
                                        :content,
                                        :author,
                                        :user_id,
                                        :font_size,
                                        :font_family,
                                        :text_color,
                                        :bg_color,
                                        :bg_opacity,
                                        :resource_id
                                        )
    end
end

app/helpers/scriptures_helper.rb
module ScripturesHelper
end

app/views/scriptures/_form.html.erb
<%= form_for(@scripture) do |f| %>
  <% if @scripture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scripture.errors.count, "error") %> prohibited this scripture from being saved:</h2>

      <ul>
      <% @scripture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scriptures/edit.html.erb
<div class='container'>
<h1>Editing Scripture</h1>

<%= render 'form' %>

<%= link_to 'Show', @scripture, :class => 'btn btn-default btn-sm' %> |
<%= link_to 'Back', scriptures_path, :class => 'btn btn-default btn-sm' %>
</div>

app/views/scriptures/index.html.erb
<div class='container'>
<p id="notice"><%= notice %></p>

<h1>Listing Scriptures</h1>
<div class='panel'>
<table class='table table-striped table-bordered'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Author</th>
      <!-- <th>User</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scriptures.each do |scripture| %>
      <tr>
        <td><%= scripture.title %></td>
        <td><%= scripture.content[0..64] %></td>
        <td><%= scripture.author %></td>
        <!-- <td><%# scripture.user.email %></td> -->
        <td><%= link_to 'Show', scripture, :class => 'btn btn-default btn-sm' %>
        <%= link_to 'Edit', edit_scripture_path(scripture), :class => 'btn btn-default btn-sm' %>
        <%= link_to 'Destroy', scripture, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Scripture', new_scripture_path, :class => 'btn btn-default btn-sm' %>
</div>

app/views/scriptures/new.html.erb
<div class='container'>
<h1>New Scripture</h1>
<%= link_to 'Back/Cancel', scriptures_path, :class => 'btn btn-default btn-sm' %>
<%= render 'form' %>

<%= link_to 'Back/Cancel', scriptures_path, :class => 'btn btn-default btn-sm' %>
</div>

app/views/scriptures/show.html.erb
<div class='container'>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @scripture.title %>
</p>

<p class='col-sm-4'>
  <strong>Content:</strong>
  <pre><%= @scripture.content %></pre>
</p>

<p>
  <strong>Author:</strong>
  <%= @scripture.author %>
</p>

<p>
  <strong>User:</strong>
  <%= @scripture.user.email %>
</p>

<%= link_to 'Edit', edit_scripture_path(@scripture), :class => 'btn btn-default btn-sm' %> |
<%= link_to 'Back', scriptures_path, :class => 'btn btn-default btn-sm' %> |
<%= link_to 'Add Another Text/Scripture', new_scripture_path, :class => 'btn btn-default btn-sm' %>

</div>