config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  get 'admin/home'

  get 'admin/new_user' => 'admin#new_user', as: :admin_new_user
  post 'admin/create_user' => 'admin#create_user', as: :admin_create_user
  get 'admin/edit' => 'admin#edit', as: :admin_edit
  patch 'admin/update' => 'admin#update', as: :admin_update

  get 'home/index'
  root 'home#index'

  resources :programmes

  resources :resources

  resources :scriptures

  resources :songs

  devise_for :users, except: :create

  resources :users, except: :create

end

app/models/programme.rb
class Programme < ActiveRecord::Base
  belongs_to :user

  has_and_belongs_to_many :resources
  # has_and_belongs_to_many :songs
  # has_and_belongs_to_many :scriptures

  has_many :programmesSongs
  has_many :songs, through: :programmesSongs
  accepts_nested_attributes_for :programmesSongs

  has_many :programmesScriptures
  has_many :scriptures, through: :programmesScriptures
  accepts_nested_attributes_for :programmesScriptures

end

app/controllers/programmes_controller.rb
class ProgrammesController < ApplicationController

  before_filter :require_login
  before_action :set_programme, only: [:show, :edit, :update, :destroy]

  # GET /programmes
  # GET /programmes.json
  def index
    @programmes = Programme.where(:user_id => current_user.id)
  end

  # GET /programmes/1
  # GET /programmes/1.json
  def show
    @programmeSongs = @programme.programmesSongs.order( :programmeOrder )
    @programmeScriptures = @programme.programmesScriptures.order( :programmeOrder )

    @featuredResources =  @programme.resources.select { |resource| resource.featured == true }
    @backgroundResources = @programme.resources.select { |resource| resource.background == true }

    @fontList = Array.new(['Courier New', 'Courier', 'Monaco', 'Arial Rounded MT Bold', 'Helvetica', 'Arial', 'sans-serif', 'Baskerville', 'Georgia', 'Garamond', 'Times New Roman', 'Times', 'serif', 'Book Antiqua', 'Bookman Old Style', 'Impact', 'Lucida Grande', 'Lucida Sans Unicode', 'Verdana', 'Helvetica Neue', 'Palatino', 'Goudy Old Style']);

  end

  # GET /programmes/new
  def new
    if !user_signed_in?
      redirect_to home_index_path()
    end
    @programme = Programme.new
    @userSongs = Song.where(:user_id => current_user.id)
    @userScriptures = Scripture.where(:user_id => current_user.id)
    @userResources = Resource.where(:user_id => current_user.id)
  end

  # GET /programmes/1/edit
  def edit
    @userSongs = Song.where(:user_id => current_user.id)
    @userScriptures = Scripture.where(:user_id => current_user.id)
    @userResources = Resource.where(:user_id => current_user.id)

    @programmeSongs = @programme.programmesSongs

  end

  # POST /programmes
  # POST /programmes.json
  def create
    @programme = Programme.new(programme_params)

    respond_to do |format|
      if @programme.save
        format.html { redirect_to @programme, notice: 'Programme was successfully created.' }
        format.json { render :show, status: :created, location: @programme }
      else
        format.html { render :new }
        format.json { render json: @programme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programmes/1
  # PATCH/PUT /programmes/1.json
  def update
    respond_to do |format|
      if @programme.update(programme_params)
        format.html { redirect_to @programme, notice: 'Programme was successfully updated.' }
        format.json { render :show, status: :ok, location: @programme }
      else
        format.html { render :edit }
        format.json { render json: @programme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programmes/1
  # DELETE /programmes/1.json
  def destroy
    @programme.destroy
    respond_to do |format|
      format.html { redirect_to programmes_url, notice: 'Programme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_programme
    @programme = Programme.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def programme_params
    params.require(:programme).permit( :title, :notes, :user_id, :scripture_ids => [], :resource_ids => [], :song_ids => [],
                                       programmesSongs_attributes: [:id, :song_id, :programme_id, :programmeOrder],
                                       programmesScriptures_attributes: [:id, :scripture_id, :programme_id, :programmeOrder]
                                       )
  end

end

app/helpers/programmes_helper.rb
module ProgrammesHelper
end

app/views/programmes/_form.html.erb
<%= form_for(@programme) do |f| %>
  <% if @programme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@programme.errors.count, "error") %> prohibited this programme from being saved:</h2>

      <ul>
      <% @programme.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class='row'>
    <div class='col-md-4'>
      <div class="field">
        <% # f.fields_for :programmeSong do |ps| %>
        <%= f.label :songs %><br />
        <i> - hold Shift or Ctrl to select multiple </i><br />
        <%= f.select :song_ids, options_for_select(
            @userSongs.map { |song|
            [song.title, song.id]
            }, @programme.song_ids ), {}, {:multiple => true, :class => "multi-select", :style => "width:300px; height: 300px;" } %>
        <% # end %>

      </div>
    </div>
    <div class='col-md-4'>
      <div class="field">
        <%= f.label :scriptures %><br />
        <i> - hold Shift or Ctrl to select multiple </i><br />
        <%= f.select :scripture_ids, options_for_select(
            @userScriptures.map { |scripture|
            [scripture.title, scripture.id]
            }, @programme.scripture_ids ), {}, {:multiple => true, :class => "multi-select", :style => "width:300px; height: 300px;" } %>
      </div>
    </div>
    <div class='col-md-4'>
      <div class="field">
        <%= f.label :resources %><br />
        <i> - hold Shift or Ctrl to select multiple </i><br />
        <%= f.select :resource_ids, options_for_select(
            @userResources.map { |resource|
            [resource.title, resource.id]
            }, @programme.resource_ids ), {}, {:multiple => true, :class => "multi-select", :style => "width:300px; height: 300px;" } %>

      </div>
    </div>

  </div>
  <div class='row'>
    <label>Schedule</label><br />
    <div class='col-sm-4'>

      <div class='panel'>
        <%= f.fields_for :programmesSongs do |ps| %>
        <%= ps.hidden_field :song_id, :value => ps.object.song_id %>
        <%= ps.hidden_field :programme_id, :value => ps.object.programme_id %>
        <%= ps.hidden_field :id, :value => ps.object.id %>

        <div class='row '>
          <div class='col-sm-5'>
            <%= ps.object.song.title %>
            <%= ps.label :programmeOrder, 'Programme Order'  %> :
          </div>
          <div class='col-sm-1'>
            <%= ps.text_field :programmeOrder, :size => 2
            %>
          </div>
        </div>
        <% end %>
      </div>
    </div>

    <div class='col-md-4'>
      <div class='panel'>
        <%= f.fields_for :programmesScriptures do |pscr| %>
        <%= pscr.hidden_field :song_id, :value => pscr.object.scripture_id %>
        <%= pscr.hidden_field :programme_id, :value => pscr.object.programme_id %>
        <%= pscr.hidden_field :id, :value => pscr.object.id %>

        <div class='row '>
          <div class='col-sm-6'>
            <%= pscr.object.scripture.title %>
            <%= pscr.label :programmeOrder, 'Programme Order'  %> :
          </div>
          <div class='col-sm-2'>
            <%= pscr.text_field :programmeOrder, :size => 2
            %>
          </div>
        </div>
        <% end %>

      </div>
    </div>
  </div>
<%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programmes/edit.html.erb
<div class='container'>
<h1>Editing Programme</h1>

<%= render 'form' %>

<%= link_to 'Show', @programme, :class => 'btn btn-default btn-sm' %> |
<%= link_to 'Back', programmes_path, :class => 'btn btn-default btn-sm' %>

</div>

app/views/programmes/index.html.erb
<div class='container'>
  <p id="notice"><%= notice %></p>

  <h1>Listing Programmes</h1>
  <div class='panel'>
    <table class='table table-striped table-bordered'>
      <thead>
        <tr>
          <th>Title</th>
          <th>Notes</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @programmes.each do |programme| %>
        <tr>
          <td><%= programme.title %></td>
          <td><%= programme.notes %></td>
          <td class='col-sm-3'><%= link_to 'Open Programme', programme, :class => 'btn btn-default btn-sm' %>
          <%= link_to 'Edit', edit_programme_path(programme), :class => 'btn btn-default btn-sm' %>
          <%= link_to 'Delete', programme, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default btn-sm' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br>

  <%= link_to 'New Programme', new_programme_path, :class => 'btn btn-default btn-sm' %>
</div>

app/views/programmes/new.html.erb
<div class='container'>
<h1>New Programme</h1>
<%= link_to 'Back to List', programmes_path, :class => 'btn btn-default btn-sm pull-right' %>

<%= render 'form' %>

<%= link_to 'Back to List', programmes_path, :class => 'btn btn-default btn-sm' %>
</div>

app/views/programmes/show.html.erb
<%= javascript_include_tag params[:controller] %>

<%= javascript_tag do %>
  <% protocol = Rails.env == 'production' ? 'https' : 'http' %>
  hostWithPort = "<%= protocol + '://' + request.host_with_port() %>";
<% end %>

<div class='container'>
  <div class='row'>
    <div class='col-sm-3'>
      <h3><%= @programme.title %></h3>
    </div>

    <div class='col-sm-3'>
      <strong>Notes:</strong>
      <div class='panel'>
        <%= @programme.notes %>
      </div>
    </div>
    <div class='col-sm-2'>
      <a class="btn btn-default btn-sm" id='loadProjectorWindow'>Open Projector Window</a>
    </div>
    <div class='col-sm-2'>
      <a class="btn btn-default btn-sm" id='closeProjectorWindow'>Close Projector Window</a>
    </div>
    <div class='col-sm-1'>
      <a class="btn btn-default btn-sm" id='goToBlank'>Blank Screen</a>
    </div>
    <div class='col-sm-1'>
            <a class='clear-background btn btn-default btn-sm' >Clear Background</a>
    </div>
  </div> <!-- /row -->

  <!-- Main control area -->
  <div class='row'>
    <div class='col-sm-3 panel panel-default' id='service_menu'>
      <div class='panel-heading'>
        <b>Songs:</b>
      </div>
      <% @programmeSongs.each do |pSong| %>
      <p class='song_scheduler'
         rel='<%= pSong.song_id %>'> <%= pSong.song.title %>
      </p>
      <% end %>
      <hr />
      <div class='panel-heading'>
        <b>Scripture & Texts:</b>
      </div>
      <% @programmeScriptures.each do |pScripture| %>
      <p class='scripture_scheduler'
         rel='<%= pScripture.scripture_id %>'>
        <%= pScripture.scripture.title %>
      </p>
      <% end %>
      <div class='panel-heading'>
        <b>Featured Media</b>
      </div>
      <% @featuredResources.each do |fResource| %>
      <p class='resource_scheduler'
         rel='<%= fResource.id %>'>
        <%= fResource.title %>
      </p>
      <% end %>
    </div>

    <div class='col-sm-3'>
      <div class='panel' id='slides'>
        <!-- dynamic jQuery content -->
      </div>
    </div>
    <div class='col-sm-4'>
      <div class='panel panel-default'>
        <div class='panel-heading'>
          <b>Live Feed</b>
        </div>
        <div class='panel-body'>
          <div id="cloneWindowBody">
            <div id="cloneWinVidContainer">
              <!-- dynamic jQuery vidoe content -->
            </div>
            <div id="cloneProjContentContainer">
              <div id="clone_lyric_block">
                <!-- dynamic jQuery content -->
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class='row'>
        <div class='panel panel-default'>
          <div class='panel-heading'><b>Live Font Options</b>
            <a id='set_font_defaults' class='pull-right btn btn-default btn-sm'>Reset to Defaults</a>
          </div>
          <div class='panel-body'>

            <div class='col-sm-6'>
              <!-- <input type="text" id='set_font_family' size='10' /> -->
              <select id='set_font_family'  >
                <% @fontList.each do |fontName| %>
                <option value="<%= fontName %>" style='font-face: <%= fontName %>;'>
                  <%= fontName %>
                </option>
                <% end %>
              </select>
              <a id='set_font_btn' class='btn btn-default btn-sm'>Set Font</a>
            </div>
            <div class='col-sm-3'>
              <input type="text" id='set_font_size' size='2' />
              <a id='set_font_size_btn' class='btn btn-default btn-sm'>Set Size</a>
            </div>
            <div class='col-sm-1'>
              <p><br /></p>
            </div>
          </div>
        </div>
      </div>

      <div class='row panel'>
        <div class='col-sm-4'>
          <label>Font Color</label>
        </div>
        <div class='col-sm-4'>
          <input type="text" id='font_color' size='5'/>
          <div class="wColorPicker-button">
            <div id='fontColorPicker' class="wColorPicker-button-color"
                 style="height: 15px;">
            </div>
          </div>
        </div>
        <div class='col-sm-3'>
          <a id='set_projector_font_color' class='btn btn-default btn-sm'>Set Font Color</a></div>
      </div>

      <div class='row panel'>
        <div class='col-sm-4'>
          <label>Background Color</label><br />
        </div>
        <div class='col-sm-4'>
          <input type="text" id='projector_bg_color' size='5' /><br />
          <div class="wColorPicker-button">
            <div id='bgPicker' class="wColorPicker-button-color"
                 style="height: 15px;">
            </div>
          </div>
        </div>
        <div class='col-sm-3'>
          <a id='set_projector_bg_color' class='btn btn-default btn-sm'>Set BG Color</a>
        </div>
      </div>

      <div class='row panel'>
        <div class='col-sm-4'>
          <label>Background Opacity</label>
        </div>
        <div class='col-sm-4'>
          <input type="text" id='projector_opacity' size='1' />%
        </div>
        <div class='col-sm-3'>
          <a id='set_projector_opacity' class='btn btn-default btn-sm'>Set Opacity</a>
        </div>
      </div>

    </div>

  </div> <!-- /row -->

  <div class='row'>
    <p>
      <div class='container-fluid'>
        <div class='panel panel-default'>
          <div class='panel-heading'>
            <strong>Media Resources:</strong>
          </div>
          <div class='panel-body'>
            <a class='clear-background btn btn-default btn-sm' >Clear Background</a><br />
            <p><br /></p>
            <% @backgroundResources.in_groups_of(4).each do |resourceRow| %>
            <% resourceRow.select! {|x| !x.nil?} %>
            <div class="row">
              <% resourceRow.each do |resource| %>
              <div class='col-sm-2'>
                <a class='media-chooser' rel='<%= resource.id %>' >
                  <% if resource.resourceType == 'video/mp4' %>
                  <video width="128" rel='<%= resource.id %>' >
                    <source src="<%= resource.location %>" type="video/mp4">
                      Your browser does not support the video tag.
                  </video>
                  <% else %>
                  <img src="<%= resource.location %>" rel='<%= resource.id %>' />
                  <% end %>
                  <br />
                  <%= resource.title %></a>
              </div>
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    <p>
  </div>
  <strong>User:</strong>
  <%= @programme.user.email %>
</p>


<%= link_to('Edit', { :action => 'edit', :id => @programme }, :class => 'btn btn-default btn-sm')  %> |
<%= link_to('Back', { :action => 'index'}, :class => 'btn btn-default btn-sm') %>
</div>
<%# the above notation seems more readable than the magic methods, e.g. edit_programme_path(@programme) %>