config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  get 'admin/home'

  get 'admin/new_user' => 'admin#new_user', as: :admin_new_user
  post 'admin/create_user' => 'admin#create_user', as: :admin_create_user
  get 'admin/edit' => 'admin#edit', as: :admin_edit
  patch 'admin/update' => 'admin#update', as: :admin_update

  get 'home/index'
  root 'home#index'

  resources :programmes

  resources :resources

  resources :scriptures

  resources :songs

  devise_for :users, except: :create

  resources :users, except: :create

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/programme.rb
class Programme < ActiveRecord::Base
  belongs_to :user

  has_and_belongs_to_many :resources
  # has_and_belongs_to_many :songs
  # has_and_belongs_to_many :scriptures

  has_many :programmesSongs
  has_many :songs, through: :programmesSongs
  accepts_nested_attributes_for :programmesSongs

  has_many :programmesScriptures
  has_many :scriptures, through: :programmesScriptures
  accepts_nested_attributes_for :programmesScriptures

end

app/models/programmeResource.rb
class ProgrammeResource < ActiveRecord::Base
  belongs_to :programme
  belongs_to :resource
end

app/models/programmes_resource.rb
class ProgrammesResource < ActiveRecord::Base
  belongs_to :programme
  belongs_to :resource
end

app/models/programmes_scripture.rb
class ProgrammesScripture < ActiveRecord::Base
  belongs_to :programme
  belongs_to :scripture
end

app/models/programmes_song.rb
class ProgrammesSong < ActiveRecord::Base
  belongs_to :programme
  belongs_to :song
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :programme

end

app/models/scripture.rb
class Scripture < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :programmes

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user

  has_many :programmeSongs
  has_many :programmes, through: :programmeSongs

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :songs
  has_many :scriptures
  has_many :resources
  has_many :programmes

  # Include default devise modules. Others available are:
  #  :registerable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_admin, only: [:show, :edit, :update]


  def home
  end

  # GET /admin/new_user
  def new_user
    @new_user = User.new
  end

  def edit
  end

  # PATCH/PUT /admin/1
  def update
    respond_to do |format|
      if @admin_user.update(admin_params)
        format.html { redirect_to :admin_home, notice: 'Admin User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # POST /users
  def create_user
    @new_user = User.new(user_params)
    if @new_user.save
      #success
      redirect_to @new_user, notice: 'User was successfully created.'
    else
      #error
      render @new_user.errors
    end
  end

  private

  def set_admin
    @admin_user = current_admin
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def admin_params
    params.require(:admin).permit(:email, :password)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/programmes_helper.rb
module ProgrammesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/scriptures_helper.rb
module ScripturesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_admin_form.html.erb
<div class='panel panel-default'>
  <div class='panel-body'>
    <%= form_for(@admin_user, :url => admin_update_path ) do |f| %>

    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :password %><br>
      <%= f.text_field :password %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

    <% end %>
  </div>
</div>

app/views/admin/_form.html.erb
<div class='panel panel-default'>
  <div class='panel-body'>
    <%= form_for(@new_user, :url => admin_create_user_path ) do |f| %>

    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :password %><br>
      <%= f.text_field :password %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

    <% end %>
  </div>
</div>

app/views/admin/create_user.html.erb
<h1>User Created</h1>

app/views/admin/edit.html.erb
<div class='container'>
<h1>Editing Admin Account</h1>

<%= render 'admin_form' %>

<%= link_to 'Back', admin_home_path %>
</div>

app/views/admin/home.html.erb
<div class="container">

<h1>Admin Dashboard</h1>

<ul>
  <li><%= link_to 'Users', users_path,
          {:class => 'btn btn-default btn-sm'} %></li>
  <li><%= link_to "Create User", admin_new_user_path,
          {:class => 'btn btn-default btn-sm'} %></li>
  <li><%= link_to "Admin Account", admin_edit_path,
          {:class => 'btn btn-default btn-sm'} %></li>
</ul>

</div>

app/views/admin/new_user.html.erb
<div class='container'>
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>WorshipOnRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/topnav' %>
<div class='container'>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
</div>

<%= yield %>

<%= render 'shared/footer' %>

</body>
</html>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h3>This media resource can be a featured slide, a background, or both:</h3>

  <div class="field">
    <%= f.label "Featured Media" %><br />
    <%= f.radio_button :featured, true %> Yes
    <%= f.radio_button :featured, false %> No <br />

    <%= f.label "Background Media" %><br />
    <%= f.radio_button :background, true %> Yes
    <%= f.radio_button :background, false %> No <br />
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>

  <div class="field">
    <%= f.label :resourceType %><br>
    <%= f.text_field :resourceType %>
  </div>

  <div class="field">
    <%= f.label :attribution %><br>
    <%= f.text_field :attribution %>
  </div>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<div class='container'>
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource, :class => 'btn btn-default btn-sm' %> |
<%= link_to 'Back', resources_path, :class => 'btn btn-default btn-sm' %>
</div>

app/views/resources/index.html.erb
<div class='container'>
<p id="notice"><%= notice %></p>

<h1>Listing Resources</h1>
<div class='panel'>
<table class='table table-striped table-bordered' >
  <thead>
    <tr>
      <th>Title</th>
      <th>Location</th>
      <th>Resource type</th>
      <th>Background</th>
      <th>Featured</th>
      <th>Attribution</th>
      <!-- <th>User</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.title %></td>
        <td><%= resource.location %></td>
        <td><%= resource.resourceType %></td>
        <td><%= resource.background ? 'Yes' : 'No' %> </td>
        <td><%= resource.featured ? 'Yes' : 'No' %></td>
        <td><%= resource.attribution %></td>
        <!-- <td><%# resource.user.email %></td> -->
        <td><%= link_to 'Show', resource, :class => 'btn btn-default btn-sm' %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource), :class => 'btn btn-default btn-sm' %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Resource', new_resource_path, :class => 'btn btn-default btn-sm' %>
</div>

app/views/resources/new.html.erb
<div class='container'>
<h1>New Resource</h1>
<%= link_to 'Back to List', resources_path, :class => 'btn btn-default btn-sm pull-right' %>

<%= render 'form' %>

<%= link_to 'Back to List', resources_path, :class => 'btn btn-default btn-sm' %>
</div>

app/views/resources/show.html.erb
<div class='container'>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @resource.title %>
</p>

<p>
  <strong>Location:</strong>
  <%= @resource.location %>
</p>

<p>
  <strong>Resourcetype:</strong>
  <%= @resource.resourceType %>
</p>

<p>
  <strong>Attribution:</strong>
  <%= @resource.attribution %>
</p>

<p>
  <strong>User:</strong>
  <%= @resource.user.email %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource), :class => 'btn btn-default btn-sm' %> |
<%= link_to 'Back', resources_path, :class => 'btn btn-default btn-sm' %> |
<%= link_to 'New Resource', new_resource_path, :class => 'btn btn-default btn-sm' %>

</div>

app/views/shared/_footer.html.erb
<!-- <footer class="footer"> -->
<!--   <div class='container'> -->
<!--     <p> -->
<!--       Powered by Ruby on Rails -->
<!--     </p> -->
<!--   </div> -->
<!-- </footer> -->

app/views/shared/_topnav.html.erb
<!--=== Top ===-->
<div class="top">
  <div class="container">
    <div class="logo">
      <div class='site-title' >
        <div class='site-title-text'>
          Worship on Rails
        </div>
      </div>

    </div>
    <div>
      <ul class="header-nav">
        <div class="browse">
          <div class="container">
            <ul class="nav navbar-nav">
              <li>
                <%= link_to "Home", home_index_path() %>
              </li>
              <% if user_signed_in? %>
              <li>
                <%= link_to "Programmes", programmes_path() %>
              </li>
              <li>
                <%= link_to "Songs", songs_path() %>
              </li>
              <li>
                <%= link_to "Scriptures & Texts", scriptures_path() %>
              </li>
              <li>
                <%= link_to "Media Resources", resources_path() %>
              </li>
              <% end %>
            </ul>

            <div class='col-sm-4 pull-right'>
              <% if user_signed_in? %>
              Logged in as <strong>
                <%= current_user.email %>
              </strong><br />
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => "btn btn-default btn-sm pull-right" %>
              <%= link_to "Account", edit_user_path(current_user),
                  {:class => 'btn btn-default btn-sm pull-right'} %>
              <% else %>
              <%=
# link_to "Sign up", new_user_registration_path, :class => "btn btn-default"
              %>
              <%= link_to "Sign in", new_user_session_path, :class => "btn btn-default" %>
              <% end %>
            </div> <!-- /auth panel -->

          </div>
        </div>
    </div>
  </div>
</div>