config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  get 'admin/home'

  get 'admin/new_user' => 'admin#new_user', as: :admin_new_user
  post 'admin/create_user' => 'admin#create_user', as: :admin_create_user
  get 'admin/edit' => 'admin#edit', as: :admin_edit
  patch 'admin/update' => 'admin#update', as: :admin_update

  get 'home/index'
  root 'home#index'

  resources :programmes

  resources :resources

  resources :scriptures

  resources :songs

  devise_for :users, except: :create

  resources :users, except: :create

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user

  has_many :programmeSongs
  has_many :programmes, through: :programmeSongs

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_filter :require_login
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.where(:user_id => current_user.id)
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(
                                   :title,
                                   :content,
                                   :license,
                                   :author,
                                   :user_id,
                                   :font_size,
                                   :font_family,
                                   :text_color,
                                   :bg_color,
                                   :bg_opacity,
                                   :resource_id
                                   )
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, :cols => "50", :rows => "20" %>
  </div>
  <div class="field">
    <%= f.label :license %><br>
    <%= f.text_field :license %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
<%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/songs/edit.html.erb
<div class='container'>
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song, :class => 'btn btn-default btn-sm' %> |
<%= link_to 'Back', songs_path, :class => 'btn btn-default btn-sm' %>
</div>

app/views/songs/index.html.erb
<div class='container'>
<p id="notice"><%= notice %></p>

<h1>Listing Songs</h1>
<div class='panel'>
<table class='table table-striped table-bordered'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>License</th>
      <th>Author</th>
      <!-- <th>User</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.content[0..64] %></td>
        <td><%= song.license %></td>
        <td><%= song.author %></td>
        <!-- <td><%# song.user.email %></td> -->
        <td ><%= link_to 'Show', song, :class => 'btn btn-default btn-sm' %>
        <%= link_to 'Edit', edit_song_path(song), :class => 'btn btn-default btn-sm' %>
        <%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Song', new_song_path, :class => 'btn btn-default btn-sm' %>
</div>

app/views/songs/new.html.erb
<div class='container'>
<h1>New Song</h1>
<%= link_to 'Cancel/Back', songs_path, :class => 'btn btn-default btn-sm pull-right' %>

<%= render 'form' %>

<%= link_to 'Cancel/Back', songs_path, :class => 'btn btn-default btn-sm' %>
</div>

app/views/songs/show.html.erb
<div class='container'>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @song.title %>
</p>

<p>
  <strong>Content:</strong>
<div class='col-sm-6'>
<pre><%= @song.content %>
</pre>
</div>
</p>

<p>
  <strong>License:</strong>
  <%= @song.license %>
</p>

<p>
  <strong>Author:</strong>
  <%= @song.author %>
</p>

<p>
  <strong>User:</strong>
  <%= @song.user.email %>
</p>

<%= link_to 'Edit', edit_song_path(@song), :class => 'btn btn-default btn-sm' %> |
<%= link_to 'Back', songs_path, :class => 'btn btn-default btn-sm' %> |
<%= link_to 'Add Another Song', new_song_path, :class => 'btn btn-default btn-sm' %>

</div>